name: aws-sam-cicd

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip freeze > requirements.txt
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: pytest
        
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Create template.yml
        run: echo "${{ secrets.AWS_SAM_TEMPLATE_YAML }}" > template.yml
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - run: |
          pip freeze > requirements.txt
          sam sync --stack-name=ome-restaurant-app
